### ISSUE TITLE
Display lots of errors...even with your example project too..

### ISSUE THREAD

**Issue by BhavinBhadani** [gilesvangruisen/Swift-YouTube-Player#13]
when i installed this project library..it displays lots of errors ...then i check your project example and same problem occurs here too....
![snip20150526_1](https://cloud.githubusercontent.com/assets/11731407/7813382/399789ec-03d8-11e5-9016-5f7de1876016.png)  

so...how to solve this..and please make some installation guide for user for your repository  
Note :  i installed this library manually

**Comment by iRoachie** [comment]
Most of these are just issues with optionals and unwrapping values. It happened
to me as well. It's because since then Apple updated Swift to 1.2 which has very
slight changes that can be easily fixed.

On Tue, May 26, 2015 at 9:25 AM, gilesvangruisen/Swift-YouTube-Player
<reply@reply.github.com>
wrote:
when i installed this project library..it displays lots of errors ...then i
check your project example and same problem occurs here too....
snip20150526_1
[https://cloud.githubusercontent.com/assets/11731407/7813382/399789ec-03d8-11e5-9016-5f7de1876016.png]
[https://cloud.githubusercontent.com/assets/11731407/7813382/399789ec-03d8-11e5-9016-5f7de1876016.png]

so...how to solve this..and please make some installation guide for user for
your repository

—
Reply to this email directly or view it on GitHub
[https://github.com/gilesvangruisen/Swift-YouTube-Player/issues/13] .[https://github.com/notifications/beacon/AFr89oUB5nW5LBZYOt-m7v7rK218qomAks5oNGvIgaJpZM4EqNCV.gif]

**Comment by BhavinBhadani** [comment]
@iRoachie Thanks for your reply...and one more thing is this library supports full screen?
