### ISSUE TITLE
Pod update 0.5

### ISSUE THREAD

**Issue by JaiKrishK** [gilesvangruisen/Swift-YouTube-Player#169]
Not able to update to version 0.5

**Comment by andrewash** [comment]
I'm seeing this as well, the Pod hasn't been updated, which means I can't depend on version 0.5+  when creating another Pod.

Could you update it on cocoapods?

Thanks!
Andrew
https://cocoapods.org/pods/YouTubePlayer

**Comment by provmusic** [comment]
+1

**Comment by robelsh** [comment]
Hello, while waiting for an update you can do that 
`  pod 'YouTubePlayer', :git => 'https://github.com/gilesvangruisen/Swift-YouTube-Player.git'`

**Comment by eveningkid** [comment]
@robelsh worked for me, thanks!

**Comment by luvacu** [comment]
We are having the same issue. The `v0.5.1` pod spec has not been pushed to the trunk. 
@gilesvangruisen  Could you please update it in Cocoapods?
Thank you!

**Comment by vdeep** [comment]
Please update in Cocoapods.

**Comment by kudzaiTnexus** [comment]
Any action on updating 0.5.1 podspec , i am unable to update to the latest pod

**Comment by gilesvangruisen** [comment]
Sorry for the delay, y'all! The other day I deployed 0.7.0 to Cocoapods which includes Swift 5 updates and uses `WKWebView` instead of the deprecated `UIWebView`. There are two rather minor breaking changes, please see README for those.

Closing this issue but let me know if you have any questions, thanks!
