### ISSUE TITLE
Example app broken

### ISSUE THREAD

**Issue by neodave** [gilesvangruisen/Swift-YouTube-Player#171]
The current example app builds but crashes with an "image not found" message. I noticed all the IBOutlets were broken so I reconnected them, but that did not stop the crash. Would love to check out your solution, but can't get example app to launch.

**Comment by gilesvangruisen** [comment]
Hi @neodave sorry for the delay. It's possible this was due to missing copy framework or not having built the library dependency. Either way, this should now be resolved. I'm doing some Spring cleaning, so I'll be closing this issue, but please comment if it comes up again. Thanks for understanding.

**Comment by neodave** [comment]
Thanks for the update and letting me know 👍
