### ISSUE TITLE
https://www.youtube.com/embed/Jm7Satp7Zqk?enablejsapi=1&widgetid=1

### ISSUE THREAD

**Issue by LathiyaViral** [gilesvangruisen/Swift-YouTube-Player#174]

**Comment by LathiyaViral** [comment]
Not able to play video

**Comment by gilesvangruisen** [comment]
Hi @LathiyaViral sorry for the delay. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue. 

Without more information, it's hard for me to know how to help you, but given the URL you posted is an embed link not a video URL, it's possible that may be the reason the video is not able to play. If you pass the video in the correct "watch" format, it should work, e.g. `https://www.youtube.com/watch?v=Jm7Satp7Zqk`.
