### ISSUE TITLE
youtube player keeps reloading on UItableview cell on scroll.

### ISSUE THREAD

**Issue by PrakashMaharjan** [gilesvangruisen/Swift-YouTube-Player#176]
Hi,

Youtube player view in UiTableView cell always reloads or flickers a bit while scrolling table view.
How can I prevent that and enable smooth scrolling of table view without the thumbnail being disappearing. I guess youtube player being web view, it always reloads when table view is scrolled and cell for row at index path is called. 

Any suggestion to fix this?

**Comment by gilesvangruisen** [comment]
Hi @PrakashMaharjan sorry for the delay, this is an interesting issue! It is likely an issue with UITableViewCell reuse, where cells instances are reused upon scroll rather than instantiated for every single item in the table view. 

Some of this is unavoidable as long you're using UITableViews, but If this is still an issue, you might consider reading more about cell reuse, and specifically two methods `dequeueReusableCellWithIdentifier` and `prepareForReuse` which help you handle this behavior.

I'm doing some Spring cleaning so I'll be closing this for now. Please comment if it continues to be an issue that you think this library should resolve. Thanks for understanding.
