### ISSUE TITLE
How to add more than one id and show prev next buttons on default UI?

### ISSUE THREAD

**Issue by anonym24** [gilesvangruisen/Swift-YouTube-Player#178]
Android YouTube player can play list of IDs: https://github.com/youtube/yt-android-player/blob/master/src/com/examples/youtubeapidemo/VideoListDemoActivity.java#L163

mb official YouTube Player Library for iOS can do it also: https://developers.google.com/youtube/v3/guides/ios_youtube_helper

but I official YouTube Player doesn't have any default controls, it just display view with video

That's why I want to use this library but it can only player one ID or playlist:

```
func loadVideoID(videoID: String)
func loadPlaylistID(playlistID: String)
```

but I need 

`func loadVideoIDs(videoIDs: String[])`

and the ability to switch between these videos (next, prev buttons)

So now this library doesn't allow to create custom playlist, it can only play real YouTube playlist (using playlist id)

**Comment by gilesvangruisen** [comment]
Hi @anonym24 sorry for the delay. I'm doing some Spring cleaning so I'm going to close this issue due to inactivity. 

It seems that the Android library you point to may be using a fundamentally different strategy to playback videos than the official Objective-C library or this library, which both use the YouTube IFrame API.

Please feel free to comment again if this continues to be an issue you think should be resolved by this library. Otherwise, I suggest building your own mechanism around this library to continues playback of a list of video IDs, as this functionality is outside of the scope of this library. Thanks for understanding.
