### ISSUE TITLE
CoreAnimation: [EAGLContext renderbufferStorage:fromDrawable:] was called from a non-main thread in an implicit transaction! Note that this may be unsafe without an explicit CATransaction or a call to [CATransaction flush].

### ISSUE THREAD

**Issue by stephaniegoldman12** [gilesvangruisen/Swift-YouTube-Player#192]
Follow the instructions but get this error? Not sure how to fix :/ can anybody help out?

**Comment by gilesvangruisen** [comment]
Hi @stephaniegoldman12, really sorry about the delay here! We're not doing any CoreAnimation or GL drawing in this library, but it's possible there was previously an internal issue within `UIWebView` and how it handled media playback. If that's the case, this should no longer be an issue as we've moved to using `WKWebView` instead due to `UIWebView`'s deprecation.

I'm going to close this for now, but please do comment again if you think this is an issue that should be resolved by this library. Thanks for understanding!
