### ISSUE TITLE
Cannot play VEVO videos

### ISSUE THREAD

**Issue by Jalsemgeest** [gilesvangruisen/Swift-YouTube-Player#28]
When I go to play a video that is under the VEVO umbrella I get a message:

> "This video contains content from VEVO.  It is restricted from playback on certain sites.  Watch on YouTube."

**Comment by gilesvangruisen** [comment]
Yes, unfortunately YouTube restricts the iFrame API from playing certain copyrighted content from VEVO.

**Comment by Jalsemgeest** [comment]
That's odd though.  I am able to play it within my browser just fine.

**Comment by memetcircus** [comment]
I experienced the same problem with Vimeo

**Comment by gilesvangruisen** [comment]
@Jalsemgeest Do you mean in your browser on Youtube.com or in your browser with the iFrame API?

**Comment by memetcircus** [comment]
I mean the iframe in my iOS app

**Comment by gilesvangruisen** [comment]
Sorry, @memetcircus. I was asking @Jalsemgeest to clarify what he meant by being able to play the VEVO video within his browser without trouble.

**Comment by Jalsemgeest** [comment]
I can play VEVO videos just fine using the iframe API in my browser and PC.

However I cannot play the VEVO videos on iOS using this.

Other videos work fine on both iOS and PC.

**Comment by gilesvangruisen** [comment]
@Jalsemgeest Gotcha. Thanks for clarifying. VEVO appears to have embed restrictions based on device, so they must be checking the user-agent of the web view. Unfortunately I don't believe there's much way around this without spoofing the user-agent, and I don't particularly want to force everyone who uses this library to break the YouTube/VEVO terms of service by bypassing their content embedding restrictions.

I'll keep this closed indefinitely. If the iframe player shows messages like this for videos you attempt to play, please know that it is, if anything, due to their (YouTube or the content owner) own restrictions on device/country/video/etc., and nothing specific to this wrapper around the iframe API.

**Comment by Jalsemgeest** [comment]
Fair enough!  Thanks a lot @gilesvangruisen!
