### ISSUE TITLE
No such module 'YouTubePlayer'

### ISSUE THREAD

**Issue by qadirsuh** [gilesvangruisen/Swift-YouTube-Player#65]
Got 

![screen shot 2016-04-04 at 1 12 22 pm](https://cloud.githubusercontent.com/assets/14326497/14241756/a596100c-fa66-11e5-95b7-d239ce11ae73.png)

/Users/qadirhussain/Downloads/Swift-YouTube-Player-master/YouTubePlayerExample/YouTubePlayerExample/ViewController.swift:10:8: No such module 'YouTubePlayer'

**Comment by JeffersonBe** [comment]
Hi @qadirsuh 

Which method did you use to install Swift-YouTube-Player? Carthage or Cocoapods?

**Comment by qadirsuh** [comment]
Cocoapods.

**Comment by Viktor112** [comment]
Hi,
I am having the same issue, I can't seem to figure out how to solve that... Imported from Cocoapods too !

**Comment by ajaysinghthakur** [comment]
i had the same problem, then i ran the youtubeplayer.framework scheme first then youtubeplayerexample   
then it works fine

**Comment by Viktor112** [comment]
Hi, Im still blocked on that... what do you mean @ajaysinghthakur please ? I have tried all possible ways to install that framework! I always end up having issue "no such module..."

**Comment by bizibizi** [comment]
I have the same

**Comment by androidexceptioncom** [comment]
The example doesnt works, i tried to copy the YoutubePlayer.swift but i had this error:

Unknown class _TtC13YouTubePlayer17YouTubePlayerView in Interface Builder file.

When i click on a button

**Comment by gilesvangruisen** [comment]
I haven't been able to reproduce this, with CocoaPods or otherwise. If you're stuck or seeing errors like `No such module 'YouTubePlayer'` or `Cannot load underlying module 'YouTubePlayer'` then I'd recommend ensuring you're using the CocoaPods generated `.xcworkspace` file. Or, try to clean the build folder with: <kbd>cmd</kbd>+<kbd>opt</kbd>+<kbd>shift</kbd>+<kbd>K</kbd>
