### ISSUE TITLE
Enable Airplay?

### ISSUE THREAD

**Issue by justinackermann** [gilesvangruisen/Swift-YouTube-Player#70]
Hi! Has anyone been able to enable Airplay playback? I have added the "webView.mediaPlaybackAllowsAirPlay = true" to the swift file manually but that does not work. Any ideas?

Thanks!

**Comment by fadylateef** [comment]
Still no solution ?

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue.

Seems like this might be possible now with the recent change to use `WKWebView`. Depending on the solution, I would consider an implementation that supports broadcasting over AirPlay. For now, please leave a comment or open a pull request if this is still something you'd like to see. Thank you.
