### ISSUE TITLE
Portrait to Landscape Animation

### ISSUE THREAD

**Issue by shakeebmajid** [gilesvangruisen/Swift-YouTube-Player#79]
YouTube videos usually animate the video and player when switching from portrait to landscape

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue. This library or the underlying web view do not dictate anything about device orientation, so it is the responsibility of your implementation to ensure your desired behavior, but please comment or open another Issue if the problem persists. Thank you.
