### ISSUE TITLE
Video is paused when app enters background.

### ISSUE THREAD

**Issue by ghost** [gilesvangruisen/Swift-YouTube-Player#88]
There is an issue with playing the video's audio when the app enters background.

I've setup my app to play background audio, this includes setting the avaudiosession, configuring the apps capability and info.plist entries. However, when I press the home button, the app pauses playback of the video. 

I can resume playing the video by manually pressing play in either control center or when the phone is locked. This is unideal, how can I stop the video from pausing when entering background?

**Comment by mertkgs** [comment]
hello,
first set up an observer in viewDidLoad method:
`NotificationCenter.default.addObserver(self, selector: #selector(ViewController.playInBackground), name: NSNotification.Name.UIApplicationDidEnterBackground, object: nil)`

and inside your playInBackground method call:
```
 func playInBackground(){
         DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(250)) {
            self.videoPlayer.play()
        }
    }
```

**Comment by gilesvangruisen** [comment]
Hi @Liquicit! This is a really good question, and I'm really sorry for slacking on the support here. 

I'm not immediately sure how I'd approach this, as I haven't dealt with background audio before on iOS. I'm really curious to hear how you got on, and what you ended up doing, if you were able to find a solution. 

The proposed solution by @mertkgs seems like it would work, but is not ideal because users would experience at least a 250ms pause. 

Depending on your solution, I'm willing to accept a PR that exposes some property like "playsInBackground" or something to add support for this.

**Comment by jr9098** [comment]
is it possible to make a delegate method that would be call  when player state will change so we can trigger play() when player state will change to pause to avoid the small video pause when app goes in background. ?

**Comment by gilesvangruisen** [comment]
Sorry for the delay here. I'm doing some Spring cleaning, so due to inactivity I'll be closing this issue.

Please leave a comment or open a pull request if this issue persists. Thank you.
