### ISSUE TITLE
isHidden is not working

### ISSUE THREAD

**Issue by kwstasna** [gilesvangruisen/Swift-YouTube-Player#93]
Hello.

I'm trying to hide the youtubeVideo by the following code

`youtubeVideo.isHidden = true`

but is not working.
Any idea?

**Comment by gilesvangruisen** [comment]
Hi @kwstasna! 

The `YouTubePlayerView` itself doesn't expose any special property for hiding itself. Are you trying to use the `UIView` property, `hidden`? If so, I think in your case you want to say `youtubeVideo.hidden = true`. Not the difference between `isHidden` and `hidden`. 

Hope this helps. I'm going to close this since it doesn't seem to be an issue with the library itself.

**Comment by kwstasna** [comment]
In swift3 its `isHidden` !
